name: format codes

on:
  workflow_call:
    inputs:
      language:
        description: 'Which language to format (python, go)'
        type: string
        required: false
        default: 'python'

jobs:
  format_python:
    if: ${{ inputs.language == 'python' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.x"
      - run: |
          pip install --upgrade pip
          pip install autoflake isort black pyupgrade
      - run: |
          autoflake -i -r --ignore-init-module-imports --remove-unused-variables --remove-duplicate-keys --remove-all-unused-imports .
          black -t py310 .
          isort -n --py 310 -m 3 --trailing-comma .
          find . -name "*.py" -exec pyupgrade --py310-plus {} \;
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format codes"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

  format_go:
    if: ${{ inputs.language == 'go' || inputs.language == 'golang' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true
          cache-dependency-path: '**/go.sum'
      - run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install mvdan.cc/gofumpt@latest
          go install github.com/segmentio/golines@latest
          go install github.com/daixiang0/gci@latest
      - run: |
          go mod tidy
          gofmt -w .
          goimports -w .
          gci write . -s standard -s default -s "prefix(main)"
          gofumpt -w -extra .
          golines --max-len=80 .
          go mod tidy
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format codes"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
